apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate-dashboard.yaml
  - certificate-overview.yaml
  - virtualservice-dashboard.yaml
  - virtualservice-overview.yaml
