apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-risingwave
resources:
  - ../../base
  - endpoints.yaml

images:
  - name: etl-pipeline
    newName: 064859874041.dkr.ecr.us-east-2.amazonaws.com/risingwave/etl-pipeline
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000

patches:
  - target: { kind: ExternalSecret, name: etl-pipeline-credentials }
    patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: op-usxpress-prod/risingwave/root
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: op-usxpress-prod/risingwave/postgres
