---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin-credentials
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: admin.password
      remoteRef:
        key: op-usxpress-dev/risingwave/argocd
        property: admin.password
    - secretKey: admin.passwordMtime
      remoteRef:
        key: op-usxpress-dev/risingwave/argocd
        property: admin.passwordMtime
