apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: grafana
  labels:
    app.kubernetes.io/managed-by: flux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "{{ .username }}"
        admin-password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: op-usxpress-dev/platform/grafana
        property: username
    - secretKey: password
      remoteRef:
        key: op-usxpress-dev/platform/grafana
        property: password
