#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# INFRA-1647 · Argo CD Git credential · op-usxpress-qa ONLY.
#
# Deliberately hardcoded to QA. Every AWS call pins --profile usx-qa and every
# kubectl call pins --context op-usxpress-qa; there is no environment switch,
# because a wizard that can be pointed at prod eventually is. The prod run is a
# separate script, written when INFRA-1636 lands and prod has an Application
# that needs a credential.
#
# Run it on WSL, from anywhere. Nothing here mutates a cluster: Flux applies the
# manifest from git, and the only write is one AWS Secrets Manager merge, behind
# a confirmation gate.

TOTAL_STAGES=9

# Values live outside the repo, 0600. The App ID and Installation ID are not
# secret; the private key is never written here at all — stage 3 takes the path
# to the .pem and reads it only at the moment of the merge.
ENV_FILE="$HOME/.config/infra-1647-argocd-qa.env"
mkdir -p "$(dirname "$ENV_FILE")"
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"

PLATFORM_REPO="${PLATFORM_REPO:-$HOME/pr-work/iaac-talos-flux-platform}"
PACK="${PACK:-$HOME/onprem-app-cicd}"
SM_SECRET="op-usxpress-qa/platform/argocd"
KUBE_QA="$HOME/.kube/op-usxpress-qa-sso.yaml"

banner "INFRA-1647 · Argo CD Git credential · op-usxpress-qa"

# ──────────────────────────────────────────────────────────────────────────
stage "Preflight — tools, access, and is the defect still there"
say "Checking what this wizard needs before it asks you to do anything."
MISSING=0
for t in aws kubectl git python3 openssl; do
  if command -v "$t" >/dev/null 2>&1; then step "$t ✓"; else warn "$t is missing"; MISSING=1; fi
done
[[ $MISSING -eq 1 ]] && { warn "install the missing tools and re-run"; exit 1; }

if [[ ! -d "$PLATFORM_REPO/.git" ]]; then
  warn "no clone at $PLATFORM_REPO"
  note "set PLATFORM_REPO=/path/to/iaac-talos-flux-platform and re-run"
  exit 1
fi
step "platform repo: $PLATFORM_REPO"

if [[ ! -f "$PACK/platform/argocd-config/op-qa/repo-creds-externalsecret.yaml" ]]; then
  warn "manifest pack not found at $PACK"
  note "get it with, FROM THE NOTES REPO — not from a platform clone, which has"
  note "no main branch:"
  note "  cd /home/doke/work/eks_code && git fetch origin"
  note "  mkdir -p ~/onprem-app-cicd && git archive origin/main wip/onprem-app-cicd \\"
  note "    | tar -x --strip-components=2 -C ~/onprem-app-cicd"
  exit 1
fi
step "manifest pack: $PACK"

if aws --profile usx-qa sts get-caller-identity >/dev/null 2>&1; then
  step "aws --profile usx-qa ✓  ($(aws --profile usx-qa sts get-caller-identity --query Account --output text))"
else
  warn "aws --profile usx-qa is not authenticated — run: aws sso login --profile usx-qa"
  exit 1
fi

if [[ -f "$KUBE_QA" ]] && KUBECONFIG="$KUBE_QA" kubectl --context op-usxpress-qa get ns argocd >/dev/null 2>&1; then
  step "op-usxpress-qa reachable ✓"
else
  warn "cannot reach op-usxpress-qa with $KUBE_QA"
  note "refresh SSO cluster access first; see the wsl-kubeconfig-churn notes"
  exit 1
fi

say ""
say "Confirming the defect is still real, rather than assuming it:"
FOUND=$(KUBECONFIG="$KUBE_QA" kubectl --context op-usxpress-qa -n argocd get secret \
          -l argocd.argoproj.io/secret-type --no-headers 2>/dev/null | wc -l)
if [[ "$FOUND" -eq 0 ]]; then
  step "no secret carries argocd.argoproj.io/secret-type — the credential gap is real"
else
  warn "$FOUND secret(s) already carry that label:"
  KUBECONFIG="$KUBE_QA" kubectl --context op-usxpress-qa -n argocd get secret \
    -l argocd.argoproj.io/secret-type
  confirm "Something already exists. Continue anyway?" || exit 0
fi
pause "Press Enter to start."

# ──────────────────────────────────────────────────────────────────────────
stage "GitHub — create the App on variant-inc"
say "Argo CD will authenticate as a GitHub App rather than a token, so there is"
say "no expiry date to forget. This is the failure that took the QA Flux source"
say "down silently for two days on 2026-08-16."
open_url "https://github.com/organizations/variant-inc/settings/apps/new"
step "GitHub App name:  argocd-onprem"
step "Homepage URL: any valid URL — https://github.com/variant-inc is fine"
step "Webhook: UNTICK 'Active'. Argo CD polls; it needs no webhook."
step "Permissions → Repository permissions → Contents: Read-only. Nothing else."
step "Where can this GitHub App be installed: 'Only on this account'"
step "Click 'Create GitHub App'."
say ""
note "The App ID is on the App's settings page, under 'App ID'."
ask APP_ID "Paste the App ID (digits only):"
if [[ ! "$APP_ID" =~ ^[0-9]+$ ]]; then
  warn "that is not a plain number — the App ID is digits only, e.g. 1234567"
  ask APP_ID "Paste the App ID again:"
fi
write_env APP_ID "$APP_ID"

# ──────────────────────────────────────────────────────────────────────────
stage "GitHub — private key and installation"
say "Two things from the App page: a private key, and the installation."
step "On the App settings page, scroll to 'Private keys' → 'Generate a private key'."
step "Your browser downloads a .pem file. Note where it landed."
say ""
step "Then: left menu → 'Install App' → Install on variant-inc."
step "Choose 'All repositories', or 'Only select repositories' with"
step "  risingwave-pipeline selected. Either works; all-repos means the next app"
step "  onboards with no credential work at all."
say ""
note "After installing you land on a URL ending /settings/installations/<number>."
note "That trailing number is the Installation ID — it is NOT the App ID."
ask INSTALL_ID "Paste the Installation ID (digits only):"
if [[ ! "$INSTALL_ID" =~ ^[0-9]+$ ]]; then
  warn "digits only, e.g. 87654321"
  ask INSTALL_ID "Paste the Installation ID again:"
fi
[[ "$INSTALL_ID" == "$APP_ID" ]] && warn "that is the same number as the App ID — they are different values; check the URL"
write_env INSTALL_ID "$INSTALL_ID"

say ""
ask PEM_PATH "Full path to the downloaded .pem:"
PEM_PATH="${PEM_PATH/#\~/$HOME}"
if [[ ! -f "$PEM_PATH" ]]; then
  warn "no file at $PEM_PATH"
  ask PEM_PATH "Path to the .pem:"
  PEM_PATH="${PEM_PATH/#\~/$HOME}"
  [[ -f "$PEM_PATH" ]] || { warn "still not found — re-run when you have it"; exit 1; }
fi
if openssl rsa -in "$PEM_PATH" -check -noout >/dev/null 2>&1 \
   || openssl pkey -in "$PEM_PATH" -noout >/dev/null 2>&1; then
  step "private key parses ✓  ($(wc -l < "$PEM_PATH") lines)"
else
  warn "openssl cannot parse $PEM_PATH — that is the file Argo CD would reject with"
  warn "'could not parse private key'. Re-download it and re-run."
  exit 1
fi
write_env PEM_PATH "$PEM_PATH"

# ──────────────────────────────────────────────────────────────────────────
stage "Secrets Manager — merge into $SM_SECRET (QA · 527101283767)"
warn "This secret already holds the Argo CD admin password."
say "put-secret-value replaces the WHOLE document, so this reads the current"
say "value, adds three keys, and shows you the key list before writing anything."
say ""
CUR=$(aws --profile usx-qa secretsmanager get-secret-value \
        --secret-id "$SM_SECRET" --query SecretString --output text)
step "current keys: $(python3 -c 'import json,sys; print(", ".join(sorted(json.load(sys.stdin))))' <<<"$CUR")"

NEW=$(APP_ID="$APP_ID" INSTALL_ID="$INSTALL_ID" PEM_PATH="$PEM_PATH" CUR="$CUR" python3 - <<'PY'
import json, os
d = json.loads(os.environ["CUR"])
d["repo.githubAppID"] = os.environ["APP_ID"]
d["repo.githubAppInstallationID"] = os.environ["INSTALL_ID"]
d["repo.githubAppPrivateKey"] = open(os.environ["PEM_PATH"]).read()
print(json.dumps(d))
PY
)
step "keys after merge: $(python3 -c 'import json,sys; print(", ".join(sorted(json.load(sys.stdin))))' <<<"$NEW")"
say ""
note "admin.password and admin.passwordMtime must both still be in that list."
note "If they are not, stop — writing would lock you out of Argo CD admin."
if confirm "Write this to $SM_SECRET in account 527101283767?"; then
  aws --profile usx-qa secretsmanager put-secret-value \
    --secret-id "$SM_SECRET" --secret-string "$NEW" >/dev/null
  step "written ✓"
  step "read back: $(aws --profile usx-qa secretsmanager get-secret-value --secret-id "$SM_SECRET" \
        --query SecretString --output text \
        | python3 -c 'import json,sys; print(", ".join(sorted(json.load(sys.stdin))))')"
else
  SKIPPED+=("Secrets Manager merge into $SM_SECRET")
  warn "skipped — the manifest will sync to nothing until this is done"
fi
unset CUR NEW
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Platform repo — the manifest, on branch op-qa"
say "One new file, plus one line in the kustomization that is already there."
cd "$PLATFORM_REPO"
git checkout op-qa >/dev/null 2>&1 || { warn "cannot check out op-qa"; exit 1; }
git pull --ff-only >/dev/null 2>&1 || warn "pull failed — check the branch is clean"
step "on branch $(git rev-parse --abbrev-ref HEAD), at $(git rev-parse --short HEAD)"

git checkout -b infra-1647-argocd-git-credential >/dev/null 2>&1 \
  || git checkout infra-1647-argocd-git-credential >/dev/null 2>&1
step "working branch: infra-1647-argocd-git-credential"

DEST="$PLATFORM_REPO/infrastructure/argocd-config"
cp "$PACK/platform/argocd-config/op-qa/repo-creds-externalsecret.yaml" "$DEST/"
step "copied repo-creds-externalsecret.yaml"

if grep -q 'repo-creds-externalsecret.yaml' "$DEST/kustomization.yaml"; then
  step "kustomization already lists it"
else
  # a file with no trailing newline swallows an appended line into the last one:
  # exactly the trap that silently merged two documents in prod's infra.yaml.
  [[ -n "$(tail -c1 "$DEST/kustomization.yaml")" ]] && printf '\n' >> "$DEST/kustomization.yaml"
  printf '  - repo-creds-externalsecret.yaml\n' >> "$DEST/kustomization.yaml"
  step "appended it to kustomization.yaml"
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Checks — before the PR, not after the merge"
cd "$DEST"
K1=$(grep -c '^kind:' repo-creds-externalsecret.yaml || true)
K2=$(kubectl kustomize . | grep -c '^kind:' || true)
K3=$(kubectl kustomize . | KUBECONFIG="$KUBE_QA" kubectl --context op-usxpress-qa apply \
       --dry-run=client -f - -o name 2>/dev/null | wc -l || true)
say "documents in the new file : $K1   (want 1)"
say "objects kustomize builds  : $K2   (want 4)"
say "objects the API accepts   : $K3   (want 4)"
if [[ "$K1" -ne 1 || "$K2" -ne 4 || "$K3" -ne 4 ]]; then
  warn "these three must agree. A mismatch means a document got merged into a"
  warn "comment, or the kustomization line landed inside another line."
  confirm "Continue anyway?" || exit 1
else
  step "all three agree ✓"
fi

say ""
say "Foreign cluster identifiers — this directory family has produced four copy"
say "defects already (INFRA-1646):"
if grep -n 'op-usxpress-dev\|op-usxpress-prod\|700736442855\|937464026810' repo-creds-externalsecret.yaml; then
  warn "the file names another cluster. Fix before pushing."
  exit 1
else
  step "clean — nothing but QA identifiers ✓"
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Raise the PR"
cd "$PLATFORM_REPO"
git add infrastructure/argocd-config/
git commit -q -m "argocd: org-scoped Git credential for variant-inc (INFRA-1647)

Argo CD on op-usxpress-qa holds no Git credential at all -- no secret carries
the argocd.argoproj.io/secret-type label -- so every Application pointing at an
internal variant-inc repository fails with 'ComparisonError: authentication
required'. It was masked until now by an Application that also pointed at a
missing path on a branch that does not exist, and so failed before it ever
authenticated.

One repo-creds secret, matched by URL prefix https://github.com/variant-inc, so
onboarding the next app needs no credential work. Authenticates as a GitHub App:
the installation token is short-lived and self-renewing, unlike the PAT whose
silent expiry took the QA Flux source down for two days on 2026-08-16.

Access remains bounded by the apps AppProject, which already allows exactly this
prefix and restricts destinations to app-*." 2>/dev/null || step "nothing new to commit"

git --no-pager log --oneline -1
say ""
if confirm "Push infra-1647-argocd-git-credential and open the PR?"; then
  git push -u origin infra-1647-argocd-git-credential
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    gh pr create --base op-qa --fill || note "open the PR in the browser instead"
  else
    note "gh not ready — open the PR against base op-qa in the browser"
  fi
  say ""
  warn "This wizard stops here until the PR is MERGED."
  pause "Merged? Press Enter to verify."
else
  SKIPPED+=("push + PR for infra-1647-argocd-git-credential")
  warn "skipped — nothing reaches the cluster until that PR merges"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Verify — and SecretSynced is not the check"
export KUBECONFIG="$KUBE_QA"
command -v flux >/dev/null 2>&1 && flux -n flux-system reconcile kustomization argocd-config --with-source || \
  note "flux CLI not present — waiting for the 10m interval instead"

say ""
say "1. ESO synced the secret:"
kubectl --context op-usxpress-qa -n argocd get externalsecret argocd-repo-creds-variant-inc || true

say ""
say "2. The LABEL is on the Secret. ESO does not copy labels from the"
say "   ExternalSecret, so without this Argo CD ignores a perfectly good"
say "   credential and says nothing:"
kubectl --context op-usxpress-qa -n argocd get secret argocd-repo-creds-variant-inc \
  -o jsonpath='{.metadata.labels}{"\n"}' || true

say ""
say "3. The url is a PREFIX of the Application's repoURL, character for character:"
kubectl --context op-usxpress-qa -n argocd get secret argocd-repo-creds-variant-inc \
  -o jsonpath='{.data.url}' 2>/dev/null | base64 -d; echo
note "want https://github.com/variant-inc — no trailing slash, no .git"

say ""
say "4. THE check — Argo CD actually reads the repository:"
kubectl --context op-usxpress-qa -n argocd get application risingwave-etl \
  -o jsonpath='{.status.sync.status}{"  "}{.status.health.status}{"\n"}' || true
note "want: Synced Healthy"

say ""
say "Still failing? The symptom names the cause:"
note "  authentication required     → the url prefix does not match (check 3)"
note "  could not parse private key → the PEM lost its newlines"
note "  404 on the installation     → the App was created but never installed"
note "  repo-server logs:  kubectl --context op-usxpress-qa -n argocd \\"
note "                       logs deploy/argocd-repo-server --tail=50"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Close out"
say "If risingwave-etl is Synced/Healthy, INFRA-1647 is done and INFRA-1648"
say "(the smoke test) is unblocked — it runs SELECT version(); SELECT 1 against"
say "risingwave-frontend, proving the chain without touching a real pipeline."
say ""
say "Prod is the identical change with op-usxpress-prod/platform/argocd in"
say "account 937464026810, and it lands with INFRA-1636, not before."
say ""
if [[ -f "$PEM_PATH" ]] && confirm "Delete the downloaded private key at $PEM_PATH?"; then
  rm -f "$PEM_PATH"
  step "deleted — Secrets Manager now holds the only copy"
else
  warn "the private key is still on disk at $PEM_PATH"
  SKIPPED+=("delete the local .pem at $PEM_PATH")
fi
note "captured values (not the key): $ENV_FILE"

finish
