#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# INFRA-1647 · Argo CD Git credential · op-usxpress-qa ONLY.
#
# Deliberately hardcoded to QA. Every AWS call pins --profile usx-qa and every
# kubectl call goes through kq(), which pins the kubeconfig AND the context
# resolved by API endpoint rather than by name; there is no environment switch,
# because a wizard that can be pointed at prod eventually is. The prod run is a
# separate script, written when INFRA-1636 lands and prod has an Application
# that needs a credential.
#
# Run it on WSL, from anywhere. Nothing here mutates a cluster: Flux applies the
# manifest from git, and the only write is one AWS Secrets Manager merge, behind
# a confirmation gate.

TOTAL_STAGES=9

# Values live outside the repo, 0600. The App ID and Installation ID are not
# secret; the private key is never written here at all — stage 3 takes the path
# to the .pem and reads it only at the moment of the merge.
ENV_FILE="$HOME/.config/infra-1647-argocd-qa.env"
mkdir -p "$(dirname "$ENV_FILE")"
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"

PLATFORM_REPO="${PLATFORM_REPO:-$HOME/pr-work/iaac-talos-flux-platform}"
PACK="${PACK:-$HOME/onprem-app-cicd}"
SM_SECRET="op-usxpress-qa/platform/argocd"
# op-usxpress-qa's API endpoint. This, not a filename and not a context name, is
# what identifies the cluster: ~/.kube here has merged multi-cluster files, and
# one of them carries prod. Prod is 10.10.82.52 — ONE DIGIT away. Read it twice.
QA_ENDPOINT="https://10.10.82.51:6443"
QA_KUBECONFIG=""
QA_CTX=""
QA_EXEC_PROFILE=""

# resolve_qa scans every kubeconfig for the context whose cluster server is
# exactly $QA_ENDPOINT. A filename that says "qa" proves nothing — op-usxpress-qa
# had no kubeconfig at all until the SSO path went live, and qa-one-eks.yaml is a
# merged file holding four servers including production.
resolve_qa() {
  local f ctx cl srv
  for f in "$HOME"/.kube/*.yaml "$HOME"/.kube/*.yml "$HOME"/.kube/config; do
    [[ -f "$f" ]] || continue
    while read -r ctx cl; do
      [[ -n "$ctx" ]] || continue
      srv=$(kubectl --kubeconfig="$f" config view \
              -o jsonpath="{.clusters[?(@.name==\"$cl\")].cluster.server}" 2>/dev/null)
      if [[ "$srv" == "$QA_ENDPOINT" ]]; then
        QA_KUBECONFIG="$f"; QA_CTX="$ctx"
        # Which AWS profile the aws-iam-authenticator exec plugin uses. It is
        # NOT necessarily the profile Secrets Manager needs, and each has its own
        # SSO session: usx-qa can be freshly logged in while this one is expired.
        local usr
        usr=$(kubectl --kubeconfig="$f" config view \
                -o jsonpath="{.contexts[?(@.name==\"$ctx\")].context.user}" 2>/dev/null)
        QA_EXEC_PROFILE=$(kubectl --kubeconfig="$f" config view --raw \
          -o jsonpath="{.users[?(@.name==\"$usr\")].user.exec.env[?(@.name=='AWS_PROFILE')].value}" 2>/dev/null)
        return 0
      fi
    done < <(kubectl --kubeconfig="$f" config view \
               -o jsonpath='{range .contexts[*]}{.name}{" "}{.context.cluster}{"\n"}{end}' 2>/dev/null)
  done
  return 1
}

# kq runs kubectl against op-usxpress-qa, pinned by BOTH file and context on
# every single call. Nothing here depends on an exported KUBECONFIG: a failed
# export leaves the previous value in place and the next command silently runs
# against whatever was there before.
kq() { kubectl --kubeconfig="$QA_KUBECONFIG" --context "$QA_CTX" "$@"; }

banner "INFRA-1647 · Argo CD Git credential · op-usxpress-qa"

# ──────────────────────────────────────────────────────────────────────────
stage "Preflight — tools, access, and is the defect still there"
say "Checking what this wizard needs before it asks you to do anything."
MISSING=0
for t in aws kubectl git python3 openssl curl; do
  if command -v "$t" >/dev/null 2>&1; then step "$t ✓"; else warn "$t is missing"; MISSING=1; fi
done
[[ $MISSING -eq 1 ]] && { warn "install the missing tools and re-run"; exit 1; }

if [[ ! -d "$PLATFORM_REPO/.git" ]]; then
  warn "no clone at $PLATFORM_REPO"
  note "set PLATFORM_REPO=/path/to/iaac-talos-flux-platform and re-run"
  exit 1
fi
step "platform repo: $PLATFORM_REPO"

if [[ ! -f "$PACK/platform/argocd-config/op-qa/repo-creds-externalsecret.yaml" ]]; then
  warn "manifest pack not found at $PACK"
  note "get it with, FROM THE NOTES REPO — not from a platform clone, which has"
  note "no main branch:"
  note "  cd /home/doke/work/eks_code && git fetch origin"
  note "  mkdir -p ~/onprem-app-cicd && git archive origin/main wip/onprem-app-cicd \\"
  note "    | tar -x --strip-components=2 -C ~/onprem-app-cicd"
  exit 1
fi
step "manifest pack: $PACK"

if aws --profile usx-qa sts get-caller-identity >/dev/null 2>&1; then
  step "aws --profile usx-qa ✓  ($(aws --profile usx-qa sts get-caller-identity --query Account --output text))"
else
  warn "aws --profile usx-qa is not authenticated — run: aws sso login --profile usx-qa"
  exit 1
fi

if resolve_qa; then
  step "op-usxpress-qa: context '$QA_CTX' in $(basename "$QA_KUBECONFIG")"
  step "endpoint: $QA_ENDPOINT  (prod is .52 — this is .51)"
else
  warn "no context anywhere in ~/.kube serves $QA_ENDPOINT"
  note "what exists right now:"
  for f in "$HOME"/.kube/*.yaml "$HOME"/.kube/*.yml "$HOME"/.kube/config; do
    [[ -f "$f" ]] || continue
    note "  $(basename "$f"): $(kubectl --kubeconfig="$f" config view \
        -o jsonpath='{.clusters[*].cluster.server}' 2>/dev/null)"
  done
  note ""
  note "corp VPN reachable?   nc -vz -w 5 10.10.82.51 6443"
  note "no kubeconfig at all? derive one from the Terraform state (streams it,"
  note "never saves it — the state holds every secret in plaintext):"
  note "  aws s3 cp s3://lazy-tf-state-425rbol87rmn6c7m/iaac/talos/op-usxpress-qa.tfstate - \\"
  note "    --profile usx-qa | jq -r '.outputs.kubeconfig.value' > \$HOME/.kube/op-usxpress-qa.yaml"
  note "  chmod 600 \$HOME/.kube/op-usxpress-qa.yaml"
  exit 1
fi

# The cluster and Secrets Manager authenticate through DIFFERENT profiles, each
# with its own SSO session. Check the cluster's one explicitly rather than
# inferring it from the usx-qa check above — that inference cost a round trip.
if [[ -n "$QA_EXEC_PROFILE" ]]; then
  if aws --profile "$QA_EXEC_PROFILE" sts get-caller-identity >/dev/null 2>&1; then
    step "cluster exec profile '$QA_EXEC_PROFILE' ✓"
  else
    warn "the cluster authenticates with AWS profile '$QA_EXEC_PROFILE', and that"
    warn "session is expired — separate from usx-qa, which is fine."
    note "  aws sso login --profile $QA_EXEC_PROFILE"
    exit 1
  fi
else
  note "exec plugin sets no AWS_PROFILE — it uses the default profile or its own args"
fi

if kq get ns argocd >/dev/null 2>&1; then
  step "argocd namespace reachable ✓"
  step "identity: $(kq auth whoami -o jsonpath='{.status.userInfo.username}' 2>/dev/null || echo unknown)"
else
  warn "found the context but cannot reach the cluster or read it"
  kq cluster-info 2>&1 | head -3 | while read -r l; do note "  $l"; done
  note ""
  note "corp VPN:        nc -vz -w 5 10.10.82.51 6443"
  note "exec plugin:     kubectl --kubeconfig=$QA_KUBECONFIG config view --raw \\"
  note "                   -o jsonpath='{.users[*].user.exec}{\"\\n\"}'"
  note "identity check:  kubectl --kubeconfig=$QA_KUBECONFIG --context $QA_CTX auth whoami"
  exit 1
fi

say ""
say "Confirming the defect is still real, rather than assuming it:"
FOUND=$(kq -n argocd get secret -l argocd.argoproj.io/secret-type --no-headers 2>/dev/null | wc -l)
if [[ "$FOUND" -eq 0 ]]; then
  step "no secret carries argocd.argoproj.io/secret-type — the credential gap is real"
else
  warn "$FOUND secret(s) already carry that label:"
  kq -n argocd get secret -l argocd.argoproj.io/secret-type
  confirm "Something already exists. Continue anyway?" || exit 0
fi
pause "Press Enter to start."

# ──────────────────────────────────────────────────────────────────────────
stage "GitHub — which credential, and mint it"
say "Argo CD needs to authenticate to variant-inc. Two ways, and which one you"
say "can use is not a preference — it depends on rights you either have or don't."
say ""

CRED_MODE="${CRED_MODE:-}"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  GH_ME=$(gh api user -q .login 2>/dev/null || echo "")
  GH_ROLE=$(gh api "orgs/variant-inc/memberships/$GH_ME" -q .role 2>/dev/null || echo "unknown")
  step "$GH_ME is '$GH_ROLE' on variant-inc"
else
  GH_ME=""; GH_ROLE="unknown"
  note "gh not authenticated — cannot check your role on variant-inc"
fi

if [[ -z "$CRED_MODE" ]]; then
  if [[ "$GH_ROLE" == "admin" ]]; then
    if confirm "Create an org-owned GitHub App (no expiry to forget)?"; then
      CRED_MODE=app
    else
      CRED_MODE=pat
    fi
  else
    warn "creating an org App needs owner rights, which you do not have."
    note "GitHub answers that settings page with 404, not 403, so it reads as a"
    note "broken link rather than a permission you're missing."
    note ""
    note "Send REQUEST-GITHUB-APP-OWNER.md to an owner — that is the durable fix."
    note "Meanwhile a PAT proves the whole delivery path today, and swapping to"
    note "the App later is three keys in the same ExternalSecret, same Secret"
    note "name: Argo CD sees a credential change, not a replacement."
    confirm "Continue with a PAT?" || exit 0
    CRED_MODE=pat
  fi
fi
write_env CRED_MODE "$CRED_MODE"

if [[ "$CRED_MODE" == "app" ]]; then
  MANIFEST="repo-creds-externalsecret.yaml"
  open_url "https://github.com/organizations/variant-inc/settings/apps/new"
  step "GitHub App name:  argocd-onprem"
  step "Homepage URL: https://github.com/variant-inc"
  step "Webhook: UNTICK 'Active'. Argo CD polls; it needs no webhook."
  step "Permissions → Repository permissions → Contents: Read-only. Nothing else."
  step "Where can this GitHub App be installed: 'Only on this account'"
  step "Click 'Create GitHub App'."
  say ""
  note "The App ID is on the App's settings page, under 'App ID'."
  ask APP_ID "Paste the App ID (digits only):"
  [[ "$APP_ID" =~ ^[0-9]+$ ]] || { warn "digits only, e.g. 1234567"; ask APP_ID "App ID:"; }
  write_env APP_ID "$APP_ID"
else
  MANIFEST="repo-creds-externalsecret-pat.yaml"
  warn "A PAT expires, and nothing on either cluster alerts when it does."
  warn "That is exactly how the QA Flux source ran two days on dead config."
  say ""
  say "Mint it on the SHARED automation account if you can reach it — usx-devops"
  say "is an org owner and already trusted here. A PAT on your own account works"
  say "today but dies with your offboarding."
  say ""
  open_url "https://github.com/settings/personal-access-tokens/new"
  step "Token name:  argocd-onprem-qa"
  step "Resource owner: variant-inc   ← NOT your personal account"
  step "Expiration: the shortest that is workable — you will be swapping it out"
  step "Repository access: 'Only select repositories' → risingwave-pipeline"
  step "  (or 'All repositories' so the next app needs no new token)"
  step "Permissions → Repository → Contents: Read-only. Nothing else."
  step "Generate. If it says the org must approve, that approval is the same ask"
  step "  as the App — send REQUEST-GITHUB-APP-OWNER.md instead."
  say ""
  ask_secret PAT_TOKEN "Paste the token (hidden):"
  [[ -n "$PAT_TOKEN" ]] || { warn "nothing pasted"; exit 1; }
fi

# ──────────────────────────────────────────────────────────────────────────
if [[ "$CRED_MODE" == "app" ]]; then
stage "GitHub — private key and installation"
say "Two things from the App page: a private key, and the installation."
step "App settings page → 'Private keys' → 'Generate a private key'."
step "Your browser downloads a .pem file. Note where it landed."
say ""
step "Then: left menu → 'Install App' → Install on variant-inc."
step "'All repositories', or 'Only select repositories' with risingwave-pipeline."
say ""
note "After installing you land on a URL ending /settings/installations/<number>."
note "That trailing number is the Installation ID — it is NOT the App ID."
ask INSTALL_ID "Paste the Installation ID (digits only):"
[[ "$INSTALL_ID" =~ ^[0-9]+$ ]] || { warn "digits only"; ask INSTALL_ID "Installation ID:"; }
[[ "$INSTALL_ID" == "$APP_ID" ]] && warn "same number as the App ID — they differ; check the URL"
write_env INSTALL_ID "$INSTALL_ID"

say ""
ask PEM_PATH "Full path to the downloaded .pem:"
PEM_PATH="${PEM_PATH/#\~/$HOME}"
if [[ ! -f "$PEM_PATH" ]]; then
  warn "no file at $PEM_PATH"
  ask PEM_PATH "Path to the .pem:"; PEM_PATH="${PEM_PATH/#\~/$HOME}"
  [[ -f "$PEM_PATH" ]] || { warn "still not found"; exit 1; }
fi
if openssl rsa -in "$PEM_PATH" -check -noout >/dev/null 2>&1 \
   || openssl pkey -in "$PEM_PATH" -noout >/dev/null 2>&1; then
  step "private key parses ✓  ($(wc -l < "$PEM_PATH") lines)"
else
  warn "openssl cannot parse $PEM_PATH — Argo CD would reject it with"
  warn "'could not parse private key'. Re-download and re-run."
  exit 1
fi
write_env PEM_PATH "$PEM_PATH"

else
stage "GitHub — prove the token can actually read the repo"
say "Not 'is it a plausible string' — can it read the thing Argo CD will read."
say "The token is never echoed and never written to disk."
say ""
HDRS=$(curl -sI -H "Authorization: Bearer $PAT_TOKEN" \
         -H "Accept: application/vnd.github+json" \
         https://api.github.com/repos/variant-inc/risingwave-pipeline/contents/deploy 2>/dev/null || true)
CODE=$(printf '%s' "$HDRS" | head -1 | awk '{print $2}')
case "$CODE" in
  200) step "reads variant-inc/risingwave-pipeline deploy/ ✓  (HTTP 200)" ;;
  404) warn "HTTP 404 — the token cannot see that repository."
       warn "Either it was scoped to other repos, or the org has not approved it."
       exit 1 ;;
  401) warn "HTTP 401 — the token is invalid or was pasted incompletely."; exit 1 ;;
  403) warn "HTTP 403 — the org blocked it, or SSO authorisation is pending."
       note "Fine-grained tokens on an enterprise org often need approval."
       exit 1 ;;
  *)   warn "unexpected response: ${CODE:-none}"; exit 1 ;;
esac

PAT_OWNER=$(curl -s -H "Authorization: Bearer $PAT_TOKEN" https://api.github.com/user \
              | python3 -c 'import json,sys; print(json.load(sys.stdin).get("login","?"))' 2>/dev/null || echo "?")
PAT_EXPIRY=$(printf '%s' "$HDRS" | grep -i 'github-authentication-token-expiration' \
              | cut -d' ' -f2- | tr -d '\r' || true)
step "owned by: $PAT_OWNER"
if [[ -n "$PAT_EXPIRY" ]]; then
  step "expires:  $PAT_EXPIRY"
  warn "Put that date on INFRA-1647 now. Nothing on this cluster will remind you."
  write_env PAT_EXPIRY "$PAT_EXPIRY"
else
  warn "no expiry reported — a token that never expires is worse, not better"
fi
[[ "$PAT_OWNER" == "$GH_ME" ]] && \
  warn "this is your personal account — a bridge, not the standing answer"
write_env PAT_OWNER "$PAT_OWNER"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Secrets Manager — merge into $SM_SECRET (QA · 527101283767)"
warn "This secret already holds the Argo CD admin password."
say "put-secret-value replaces the WHOLE document, so this reads the current"
say "value, adds keys, and shows you the key list before writing anything."
say ""
CUR=$(aws --profile usx-qa secretsmanager get-secret-value \
        --secret-id "$SM_SECRET" --query SecretString --output text)
step "current keys: $(python3 -c 'import json,sys; print(", ".join(sorted(json.load(sys.stdin))))' <<<"$CUR")"

if [[ "$CRED_MODE" == "app" ]]; then
  NEW=$(APP_ID="$APP_ID" INSTALL_ID="$INSTALL_ID" PEM_PATH="$PEM_PATH" CUR="$CUR" python3 -c '
import json, os
d = json.loads(os.environ["CUR"])
d["repo.githubAppID"] = os.environ["APP_ID"]
d["repo.githubAppInstallationID"] = os.environ["INSTALL_ID"]
d["repo.githubAppPrivateKey"] = open(os.environ["PEM_PATH"]).read()
print(json.dumps(d))
')
else
  NEW=$(PAT_OWNER="$PAT_OWNER" PAT_TOKEN="$PAT_TOKEN" CUR="$CUR" python3 -c '
import json, os
d = json.loads(os.environ["CUR"])
# Any non-empty username works when the password is a PAT; the real account is
# recorded so the next person knows whose credential this is.
d["repo.username"] = os.environ["PAT_OWNER"]
d["repo.password"] = os.environ["PAT_TOKEN"]
print(json.dumps(d))
')
fi
step "keys after merge: $(python3 -c 'import json,sys; print(", ".join(sorted(json.load(sys.stdin))))' <<<"$NEW")"
say ""
note "admin.password and admin.passwordMtime must both still be in that list."
note "If they are not, stop — writing would lock you out of Argo CD admin."
if confirm "Write this to $SM_SECRET in account 527101283767?"; then
  aws --profile usx-qa secretsmanager put-secret-value \
    --secret-id "$SM_SECRET" --secret-string "$NEW" >/dev/null
  step "written ✓"
  step "read back: $(aws --profile usx-qa secretsmanager get-secret-value --secret-id "$SM_SECRET" \
        --query SecretString --output text \
        | python3 -c 'import json,sys; print(", ".join(sorted(json.load(sys.stdin))))')"
else
  SKIPPED+=("Secrets Manager merge into $SM_SECRET")
  warn "skipped — the manifest will sync to nothing until this is done"
fi
unset CUR NEW PAT_TOKEN
pause

stage "Platform repo — the manifest, on branch op-qa"
say "One new file, plus one line in the kustomization that is already there."
cd "$PLATFORM_REPO"
git checkout op-qa >/dev/null 2>&1 || { warn "cannot check out op-qa"; exit 1; }
git pull --ff-only >/dev/null 2>&1 || warn "pull failed — check the branch is clean"
step "on branch $(git rev-parse --abbrev-ref HEAD), at $(git rev-parse --short HEAD)"

git checkout -b infra-1647-argocd-git-credential >/dev/null 2>&1 \
  || git checkout infra-1647-argocd-git-credential >/dev/null 2>&1
step "working branch: infra-1647-argocd-git-credential"

DEST="$PLATFORM_REPO/infrastructure/argocd-config"
cp "$PACK/platform/argocd-config/op-qa/$MANIFEST" "$DEST/"
step "copied $MANIFEST   (credential mode: $CRED_MODE)"

if grep -q "$MANIFEST" "$DEST/kustomization.yaml"; then
  step "kustomization already lists it"
else
  # a file with no trailing newline swallows an appended line into the last one:
  # exactly the trap that silently merged two documents in prod's infra.yaml.
  [[ -n "$(tail -c1 "$DEST/kustomization.yaml")" ]] && printf '\n' >> "$DEST/kustomization.yaml"
  printf '  - %s\n' "$MANIFEST" >> "$DEST/kustomization.yaml"
  step "appended it to kustomization.yaml"
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Checks — before the PR, not after the merge"
cd "$DEST"
K1=$(grep -c '^kind:' "$MANIFEST" || true)
K2=$(kubectl kustomize . | grep -c '^kind:' || true)
K3=$(kubectl kustomize . | kq apply --dry-run=client -f - -o name 2>/dev/null | wc -l || true)
say "documents in the new file : $K1   (want 1)"
say "objects kustomize builds  : $K2   (want 4)"
say "objects the API accepts   : $K3   (want 4)"
if [[ "$K1" -ne 1 || "$K2" -ne 4 || "$K3" -ne 4 ]]; then
  warn "these three must agree. A mismatch means a document got merged into a"
  warn "comment, or the kustomization line landed inside another line."
  confirm "Continue anyway?" || exit 1
else
  step "all three agree ✓"
fi

say ""
say "Foreign cluster identifiers — this directory family has produced four copy"
say "defects already (INFRA-1646):"
if grep -n 'op-usxpress-dev\|op-usxpress-prod\|700736442855\|937464026810' "$MANIFEST"; then
  warn "the file names another cluster. Fix before pushing."
  exit 1
else
  step "clean — nothing but QA identifiers ✓"
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Raise the PR"
cd "$PLATFORM_REPO"
git add infrastructure/argocd-config/
git commit -q -m "argocd: org-scoped Git credential for variant-inc (INFRA-1647)

Argo CD on op-usxpress-qa holds no Git credential at all -- no secret carries
the argocd.argoproj.io/secret-type label -- so every Application pointing at an
internal variant-inc repository fails with 'ComparisonError: authentication
required'. It was masked until now by an Application that also pointed at a
missing path on a branch that does not exist, and so failed before it ever
authenticated.

One repo-creds secret, matched by URL prefix https://github.com/variant-inc, so
onboarding the next app needs no credential work. Authenticates as a GitHub App:
the installation token is short-lived and self-renewing, unlike the PAT whose
silent expiry took the QA Flux source down for two days on 2026-08-16.

Access remains bounded by the apps AppProject, which already allows exactly this
prefix and restricts destinations to app-*." 2>/dev/null || step "nothing new to commit"

git --no-pager log --oneline -1
say ""
if confirm "Push infra-1647-argocd-git-credential and open the PR?"; then
  git push -u origin infra-1647-argocd-git-credential
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    gh pr create --base op-qa --fill || note "open the PR in the browser instead"
  else
    note "gh not ready — open the PR against base op-qa in the browser"
  fi
  say ""
  warn "This wizard stops here until the PR is MERGED."
  pause "Merged? Press Enter to verify."
else
  SKIPPED+=("push + PR for infra-1647-argocd-git-credential")
  warn "skipped — nothing reaches the cluster until that PR merges"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Verify — and SecretSynced is not the check"
command -v flux >/dev/null 2>&1 \
  && KUBECONFIG="$QA_KUBECONFIG" flux --context "$QA_CTX" -n flux-system \
       reconcile kustomization argocd-config --with-source \
  || note "flux CLI not present or reconcile failed — waiting for the 10m interval instead"

say ""
say "1. ESO synced the secret:"
kq -n argocd get externalsecret argocd-repo-creds-variant-inc || true

say ""
say "2. The LABEL is on the Secret. ESO does not copy labels from the"
say "   ExternalSecret, so without this Argo CD ignores a perfectly good"
say "   credential and says nothing:"
kq -n argocd get secret argocd-repo-creds-variant-inc \
  -o jsonpath='{.metadata.labels}{"\n"}' || true

say ""
say "3. The url is a PREFIX of the Application's repoURL, character for character:"
kq -n argocd get secret argocd-repo-creds-variant-inc \
  -o jsonpath='{.data.url}' 2>/dev/null | base64 -d; echo
note "want https://github.com/variant-inc — no trailing slash, no .git"

say ""
say "4. THE check — Argo CD actually reads the repository:"
kq -n argocd get application risingwave-etl \
  -o jsonpath='{.status.sync.status}{"  "}{.status.health.status}{"\n"}' || true
note "want: Synced Healthy"

say ""
say "Still failing? The symptom names the cause:"
note "  authentication required     → the url prefix does not match (check 3)"
note "  could not parse private key → the PEM lost its newlines"
note "  404 on the installation     → the App was created but never installed"
note "  repo-server logs:  kubectl --kubeconfig=$QA_KUBECONFIG --context $QA_CTX \\"
note "                       -n argocd logs deploy/argocd-repo-server --tail=50"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Close out"
say "If risingwave-etl is Synced/Healthy, INFRA-1647 is done and INFRA-1648"
say "(the smoke test) is unblocked — it runs SELECT version(); SELECT 1 against"
say "risingwave-frontend, proving the chain without touching a real pipeline."
say ""
say "Prod is the identical change with op-usxpress-prod/platform/argocd in"
say "account 937464026810, and it lands with INFRA-1636, not before."
say ""
if [[ -f "$PEM_PATH" ]] && confirm "Delete the downloaded private key at $PEM_PATH?"; then
  rm -f "$PEM_PATH"
  step "deleted — Secrets Manager now holds the only copy"
else
  warn "the private key is still on disk at $PEM_PATH"
  SKIPPED+=("delete the local .pem at $PEM_PATH")
fi
note "captured values (not the key): $ENV_FILE"

finish
