#!/usr/bin/env bash
# Turn an AWS Identity Center SAML metadata XML into the Argo CD dex connector block.
#
#   scripts/dex-saml-from-metadata.sh ~/Downloads/AWS_SSO_metadata.xml op-dev
#
# Emits YAML to paste into infrastructure/argocd/helmrelease.yaml under spec.values.
# Nothing here is secret: caData is the IdP's PUBLIC signing certificate, so the
# block belongs in git and needs no ExternalSecret -- which also means argocd-secret
# is never touched and op-dev's server.secretkey survives.
set -euo pipefail

XML="${1:-}"; ENV="${2:-op-dev}"
case "$ENV" in
  op-dev)  HOST="argocd.op-dev.usxpress.io" ;;
  op-qa)   HOST="argocd.op-qa.usxpress.io" ;;
  op-prod) HOST="argocd.op-prod.usxpress.io" ;;
  *) echo "!! env must be op-dev, op-qa or op-prod (got '$ENV')" >&2; exit 2 ;;
esac
[ -f "$XML" ] || { echo "!! no such file: ${XML:-<none given>}" >&2
                   echo "   usage: $0 <metadata.xml> [op-dev|op-qa|op-prod]" >&2; exit 2; }
OUT="${OUT:-$HOME/argocd-dex-saml-$ENV.yaml}"

python3 - "$XML" "$OUT" "https://$HOST/api/dex/callback" <<'PYEOF'
import base64, re, sys, xml.etree.ElementTree as ET
meta, out, callback = sys.argv[1], sys.argv[2], sys.argv[3]
root = ET.parse(meta).getroot()

# HTTP-Redirect, not HTTP-POST. Dex initiates with a redirect binding.
sso = None
for s in root.iter("{urn:oasis:names:tc:SAML:2.0:metadata}SingleSignOnService"):
    if s.get("Binding", "").endswith("HTTP-Redirect"):
        sso = s.get("Location"); break
if sso is None:
    sys.exit("no HTTP-Redirect SingleSignOnService in the metadata")

certs = [c.text for c in root.iter(
    "{http://www.w3.org/2000/09/xmldsig#}X509Certificate") if c.text]
if not certs:
    sys.exit("no X509Certificate in the metadata")

der = re.sub(r"\s+", "", certs[0])
pem = ("-----BEGIN CERTIFICATE-----\n"
       + "\n".join(der[i:i+64] for i in range(0, len(der), 64))
       + "\n-----END CERTIFICATE-----\n")
# caData is base64 OF THE PEM. The XML already holds base64 DER -- using that
# directly gives "failed to parse CA" at login and nothing sooner.
ca = base64.b64encode(pem.encode()).decode()

open(out, "w").write("""# INFRA-1639 step 3 -- generated by scripts/dex-saml-from-metadata.sh
# Paste under spec.values in infrastructure/argocd/helmrelease.yaml.
# NO CLIENT SECRET: caData is the IdP's public signing certificate.
    dex:
      enabled: true
    configs:
      cm:
        dex.config: |
          connectors:
            - type: saml
              id: aws
              name: AWS IAM Identity Center
              config:
                ssoURL: %s
                # entityIssuer MUST equal the "Application SAML audience" set in
                # Identity Center, character for character.
                entityIssuer: %s
                redirectURI: %s
                usernameAttr: email
                emailAttr: email
                groupsAttr: groups
                caData: |
                  %s
""" % (sso, callback, callback, ca))
print("  ssoURL : %s" % sso)
print("  caData : %d chars" % len(ca))
print("  written: %s" % out)
PYEOF

echo
echo "-- round-trip check: does caData decode to a real certificate? --"
python3 - "$OUT" <<'PYEOF'
import base64, re, subprocess, sys, tempfile
t = open(sys.argv[1]).read()
ca = re.search(r"caData: \|\n\s+(\S+)", t).group(1)
pem = base64.b64decode(ca).decode()
with tempfile.NamedTemporaryFile("w", suffix=".pem", delete=False) as f:
    f.write(pem); path = f.name
try:
    subj = subprocess.run(["openssl", "x509", "-in", path, "-noout", "-subject", "-enddate"],
                          capture_output=True, text=True)
    print("  " + subj.stdout.strip().replace("\n", "\n  ") if subj.returncode == 0
          else "  !! openssl could not parse it: " + subj.stderr.strip())
except FileNotFoundError:
    print("  (openssl not on PATH -- skipped)")
PYEOF
echo
echo "Next: paste $OUT into infrastructure/argocd/helmrelease.yaml on branch $ENV,"
echo "open a PR, merge, reconcile, then LOG IN. A green HelmRelease proves nothing."
