#!/usr/bin/env bash
# Reset op-usxpress-qa's ETL state so the delivery path can be re-tested from clean.
#
#   bash scripts/qa-etl-reset.sh              # report only, changes nothing
#   bash scripts/qa-etl-reset.sh --confirm    # empties pipeline_applied
#
# ONLY op-qa. Resolves the cluster BY ENDPOINT (10.10.82.51) via lib-onprem-ctx.sh and
# refuses to run anywhere else -- there is no flag to point this at another cluster.
#
# What it does NOT do, deliberately:
#   * It does not delete the Argo CD Application. `risingwave-etl` is generated by the
#     onprem-apps ApplicationSet, so deleting it just makes the controller recreate it --
#     and the Application is the mechanism under test, not the state under test.
#   * It does not drop catalog objects. If RisingWave holds sources/MVs/sinks, dropping
#     them CASCADEs into dependents and is a deliberate act, not a reset. This script
#     REFUSES to run in that case and tells you what it found.
#   * It does not touch the `risingwave` namespace's platform workloads.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source scripts/lib-onprem-ctx.sh

CONFIRM=false
[ "${1:-}" = "--confirm" ] && CONFIRM=true

onprem_resolve_ctx op-qa || exit 2
K() { kubectl --kubeconfig="$ONPREM_KC" --context="$ONPREM_CTX" "$@"; }

NS=risingwave
POD=$(K -n "$NS" get pods -o json | jq -r '
  [.items[] | select(.status.phase=="Running")
   | select([.spec.containers[].image] | map(test("postgres")) | any)
   | .metadata.name] | first // empty')
[ -n "$POD" ] || { echo "!! no running postgres pod in ${NS} on op-qa" >&2; exit 2; }
CTR=$(K -n "$NS" get pod "$POD" -o json | jq -r '[.spec.containers[]|select(.image|test("postgres"))|.name]|first')

PW=""; USER=""
for sec in $(K -n "$NS" get secrets -o name | sed 's|secret/||'); do
  for key in $(K -n "$NS" get secret "$sec" -o go-template='{{range $k,$v := .data}}{{$k}} {{end}}' 2>/dev/null); do
    case "$key" in *assword*) ;; *) continue ;; esac
    cand=$(K -n "$NS" get secret "$sec" -o go-template="{{index .data \"$key\"}}" | base64 -d 2>/dev/null) || continue
    for u in risingwave postgres rwadmin; do
      if K -n "$NS" exec "$POD" -c "$CTR" -- env PGPASSWORD="$cand" psql -h localhost -U "$u" -d postgres -tAc 'SELECT 1' 2>/dev/null | tr -d '[:space:]' | grep -qx 1; then
        PW="$cand"; USER="$u"; break 3
      fi
    done
  done
done
[ -n "$PW" ] || { echo "!! could not open postgres:5432 on op-qa" >&2; exit 2; }
P() { K -n "$NS" exec "$POD" -c "$CTR" -- env PGPASSWORD="$PW" psql -h localhost -U "$USER" -d risingwave -tAF'|' -c "$1" 2>/dev/null; }

echo "cluster : op-usxpress-qa (10.10.82.51)  ·  ${POD}/${CTR} as ${USER}"
echo

# ---- guard: the catalog must already be empty. Dropping objects is not a reset.
RWPW=$(K -n "$NS" get secret pg-credentials -o go-template='{{index .data "password"}}' | base64 -d)
Q() { K -n "$NS" exec "$POD" -c "$CTR" -- env PGPASSWORD="$RWPW" psql -h risingwave-frontend -p 4567 -U root -d dev -tAc "$1" 2>/dev/null; }
probe=$(Q 'SELECT 1;')
[ "$(printf '%s' "$probe" | tr -d '[:space:]')" = "1" ] || { echo "!! cannot query RisingWave -- refusing to act blind" >&2; exit 2; }
objs=$(Q "SELECT (SELECT count(*) FROM rw_catalog.rw_sources)
              + (SELECT count(*) FROM rw_catalog.rw_materialized_views)
              + (SELECT count(*) FROM rw_catalog.rw_sinks);" | tr -d '[:space:]')
echo "RisingWave catalog objects (sources + MVs + sinks): ${objs}"
if [ "${objs:-0}" -ne 0 ]; then
  echo
  echo "!! REFUSING. The catalog is not empty, and dropping objects CASCADEs into their"
  echo "   dependents. That is a deliberate act with a review, not part of a reset."
  echo "   Inventory it first:  bash scripts/rw-etl-inventory.sh"
  exit 1
fi

echo
echo "pipeline_applied, before:"
P "SELECT path, left(sha256,12), applied_at, applied_by FROM pipeline_applied ORDER BY applied_at;" | sed 's/^/  /'
n=$(P "SELECT count(*) FROM pipeline_applied;" | tr -d '[:space:]')
echo "  (${n} row(s))"

if [ "$CONFIRM" != true ]; then
  echo
  echo "Report only -- nothing changed. Re-run with --confirm to empty the table."
  echo "Why it matters: apply.sh skips any file whose hash is recorded here. While the"
  echo "smoke row stands, smoke/001-connectivity.rw will never re-run."
  exit 0
fi

TS=$(P "SELECT to_char(now(),'YYYYMMDD-HH24MISS');" | tr -d '[:space:]')
OUT="$HOME/qa-pipeline_applied-${TS}.bak"
P "SELECT path||'|'||sha256||'|'||applied_at||'|'||applied_by FROM pipeline_applied;" > "$OUT"
echo
echo "backed up to ${OUT}"
P "DELETE FROM pipeline_applied;" >/dev/null
echo "after: $(P "SELECT count(*) FROM pipeline_applied;" | tr -d '[:space:]') row(s)"
echo
echo "Next: the QA overlay still has PIPELINE_DIR=/pipeline/smoke. Until the Phase 1 MR"
echo "lands and flips it to /pipeline/pipelines, a sync re-applies the smoke test only."
