#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Keep the library's .env helpers away from the repo: nothing here belongs in a
# file on disk, least of all the API secret.
ENV_FILE="$(mktemp -d)/wizard.env"

SA="sa-81m660q"                 # QA's existing service account -- do NOT create a new one
KAFKA_CLUSTER="lkc-19mn63"      # QA Kafka cluster
SR_HOST="psrc-yorrp.us-east-2.aws.confluent.cloud"
SECRET_ID="op-usxpress-qa/risingwave/kafka"
PROFILE="usx-qa"
REGION="us-east-2"
SUBJECT="qa_brand_management_cdc_brand_avro-value"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

banner "QA schema-registry access for RisingWave"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: is this still the problem?"
for t in aws jq curl; do
  command -v "$t" >/dev/null 2>&1 || { warn "$t is not installed. Install it and re-run."; exit 3; }
done
say "Reading $SECRET_ID (profile $PROFILE) -- key NAMES and lengths only."
if ! CUR=$(aws secretsmanager get-secret-value --profile "$PROFILE" --region "$REGION" \
             --secret-id "$SECRET_ID" --query SecretString --output text 2>/dev/null); then
  warn "cannot read the secret. Run: aws sso login --profile $PROFILE"
  exit 3
fi
jq -r 'to_entries[] | "    \(.key) = \(if (.value|tostring|length)==0 then "EMPTY" else "set (\(.value|tostring|length) chars)" end)"' <<<"$CUR"
EMPTY_COUNT=$(jq -r '[to_entries[] | select(.key|test("schema_registry")) | select((.value|tostring|length)==0)] | length' <<<"$CUR")
echo
if [[ "$EMPTY_COUNT" == "0" ]]; then
  say "All three schema-registry fields are already populated."
  confirm "Overwrite them anyway?" || { say "Nothing to do. Run scripts/verify-qa-schema-registry.sh to test what is there."; exit 0; }
else
  say "$EMPTY_COUNT of 3 schema-registry fields are empty. That is what we are fixing."
fi
note "service account $SA   kafka cluster $KAFKA_CLUSTER   registry $SR_HOST"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Choose your route: CLI or console"
say "The Confluent CLI is not installed on this machine."
step "CLI  -- installs to ~/.local/bin, scriptable, exact commands."
step "web  -- Confluent Cloud console, no install."
ask ROUTE "Type cli or web:"
if [[ "$ROUTE" == "cli" ]]; then
  say "Installing the Confluent CLI to ~/.local/bin ..."
  confirm "Install it now?" && {
    mkdir -p "$HOME/.local/bin"
    curl -sL --http1.1 https://cnfl.io/cli | sh -s -- -b "$HOME/.local/bin" latest || warn "install failed; fall back to the web route"
    export PATH="$HOME/.local/bin:$PATH"
    command -v confluent >/dev/null 2>&1 && say "confluent $(confluent version 2>/dev/null | head -1)"
  }
  step "Log in now, in this terminal:  confluent login"
  pause "Press Enter once you are logged in"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Find the Schema Registry cluster id (lsrc-...)"
say "$SR_HOST is the endpoint. The API key is issued against the cluster ID, which"
say "looks like lsrc-xxxxx. They are different strings."
if [[ "$ROUTE" == "cli" ]] && command -v confluent >/dev/null 2>&1; then
  step "Run:  confluent environment list       (note the env that holds $KAFKA_CLUSTER)"
  step "Then: confluent environment use <env-id>"
  step "Then: confluent schema-registry cluster describe"
  note "The describe output shows the cluster ID and the endpoint; match the endpoint above."
else
  open_url "https://confluent.cloud/environments"
  step "Open the environment that contains Kafka cluster $KAFKA_CLUSTER."
  step "Open Stream Governance / Schema Registry for that environment."
  step "The cluster ID (lsrc-...) is shown on that page; confirm its endpoint matches $SR_HOST."
  warn "Confluent moves this page around between releases. If the wording differs, look for"
  warn "whatever page shows the registry's endpoint -- the ID is always beside it."
fi
ask SR_CLUSTER "Paste the Schema Registry cluster id (lsrc-...):"
[[ "$SR_CLUSTER" =~ ^lsrc- ]] || { warn "that does not look like an lsrc- id; re-run when you have it"; exit 4; }

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create the API key for $SA"
warn "The secret is shown ONCE. Have it on screen before you continue."
if [[ "$ROUTE" == "cli" ]] && command -v confluent >/dev/null 2>&1; then
  say "Run this, then paste the two values below:"
  echo
  say "  confluent api-key create --resource $SR_CLUSTER --service-account $SA \\"
  say "    --description 'op-usxpress-qa risingwave schema registry'"
  echo
else
  open_url "https://confluent.cloud/environments"
  step "Schema Registry → API keys → Add key."
  step "Choose GRANULAR access, then select the EXISTING service account $SA."
  step "Do not create a new service account -- QA already has one and its Kafka key works."
  step "Description: op-usxpress-qa risingwave schema registry"
fi
ask       SR_KEY    "Paste the API key:"
ask_secret SR_SECRET "Paste the API secret (hidden):"
[[ -n "$SR_KEY" && -n "$SR_SECRET" ]] || { warn "both values are required"; exit 4; }
say "captured: key ${#SR_KEY} chars, secret ${#SR_SECRET} chars"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Grant the service account read on the registry"
warn "This is the step people skip. A key WITHOUT a role binding authenticates and"
warn "then returns 403 -- which looks exactly like a wrong key, so the usual reaction"
warn "is to issue another key that also 403s."
if [[ "$ROUTE" == "cli" ]] && command -v confluent >/dev/null 2>&1; then
  say "  confluent iam rbac role-binding create \\"
  say "    --principal User:$SA --role DeveloperRead \\"
  say "    --schema-registry-cluster $SR_CLUSTER --subject $SUBJECT"
  note "Use --role ResourceOwner or a cluster-wide binding if you want it to cover"
  note "every subject rather than just Brand's."
else
  step "Accounts & access → service account $SA → Access → Add role assignment."
  step "Scope it to Schema Registry cluster $SR_CLUSTER, role DeveloperRead."
  step "Either the whole registry, or at least subject $SUBJECT."
fi
pause "Press Enter once the role assignment is saved"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Write the three values into Secrets Manager"
say "Merging into $SECRET_ID -- the six populated fields are preserved."
NEW=$(jq --arg e "https://$SR_HOST" --arg k "$SR_KEY" --arg s "$SR_SECRET" \
      '.kafka__schema_registry_endpoint=$e | .kafka__schema_registry_api_key=$k | .kafka__schema_registry_api_secret=$s' <<<"$CUR")
BEFORE=$(jq -r 'to_entries | map(select((.value|tostring|length)>0)) | length' <<<"$CUR")
AFTER=$(jq -r  'to_entries | map(select((.value|tostring|length)>0)) | length' <<<"$NEW")
KEYS_BEFORE=$(jq -r 'keys|length' <<<"$CUR"); KEYS_AFTER=$(jq -r 'keys|length' <<<"$NEW")
say "populated fields: $BEFORE → $AFTER     total keys: $KEYS_BEFORE → $KEYS_AFTER"
[[ "$KEYS_BEFORE" == "$KEYS_AFTER" ]] || { warn "key count changed -- refusing to write"; exit 5; }
[[ "$AFTER" == "9" ]] || warn "expected 9 populated fields after the merge, got $AFTER"
if confirm "Write this to $SECRET_ID in $PROFILE?"; then
  aws secretsmanager put-secret-value --profile "$PROFILE" --region "$REGION" \
    --secret-id "$SECRET_ID" --secret-string "$NEW" >/dev/null
  say "written."
  aws secretsmanager get-secret-value --profile "$PROFILE" --region "$REGION" \
    --secret-id "$SECRET_ID" --query SecretString --output text \
    | jq -r 'to_entries[] | select(.key|test("schema_registry")) | "    \(.key) = \(if (.value|tostring|length)==0 then "STILL EMPTY" else "set (\(.value|tostring|length) chars)" end)"'
else
  SKIPPED+=("write the three schema-registry values into $SECRET_ID")
  warn "not written"
fi
unset SR_SECRET NEW
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify -- a key that exists is not a key that works"
say "Running scripts/verify-qa-schema-registry.sh: it separates 401 (wrong key),"
say "403 (no role binding), and 200-but-Brand's-subject-missing."
echo
bash "$HERE/verify-qa-schema-registry.sh" "$PROFILE" || warn "verification did not pass -- read the FAIL line above before telling anyone this is done"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Prod: do NOT do this by hand"
warn "op-usxpress-prod/risingwave/kafka does not exist at all -- dev and QA have one, prod has none."
say "These Secrets Manager records are created by Terraform in iaac-risingwave-onprem"
say "and deployed through Octopus. Creating prod's by hand is drift that nothing"
say "reproduces, and the next apply may not keep it."
echo
step "Raise it as a Terraform change: add the prod kafka secret to secrets.tf."
step "Ask Confluent for a prod service account key + role binding at the same time."
step "Then fill the values the same way this wizard just did for QA."
note "Recorded in wip/rw-etl-promotion/CONFLUENT-QA-SR-REQUEST.md"
pause

finish
