#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Onboard Timothy Preble to op-usxpress-dev as a NAMESPACE super-user.
#
# Scope, from the Phase 1 handoff record: "Tim's scope: super-user in the risingwave
# namespace only. Not cluster-wide. Least privilege." His work now lives in
# risingwave-2, so both namespaces are bound.
#
# DEV ONLY. Every kubectl call below is pinned to the context whose server is
# 10.10.82.50 and the wizard refuses to run against anything else. Nothing here
# touches op-usxpress-qa (.51) or op-usxpress-prod (.52).
#
# Two departures from docs/runbooks/onprem_cluster_access_runbook.md, both deliberate:
#
#   1. The runbook's blocks use `base64 -w 0`, which is GNU-only and FAILS on macOS.
#      Tim is on a Mac. Everything sent to him below uses portable forms.
#   2. The runbook binds new users to O=onprem-platform-users, which is the
#      cluster-wide READ tier. That contradicts the recorded scope, so Tim's cert
#      carries O=risingwave-users -- a group with no bindings anywhere -- and his
#      access comes entirely from the two namespaced RoleBindings in stage 5.
#      His group therefore grants nothing on its own, which is the point.

# RBAC binds to a USERNAME STRING. The user does not have to exist, hold a cert,
# or ever have logged in -- and `auth can-i --as=` verifies the grant the same way
# either order. So the permission model can be landed and proved while Tim is away,
# leaving only CSR -> sign -> send for the day he is back.
MODE=full
case "${1:-}" in
  --rbac-only) MODE=rbac-only ;;
  "") ;;
  *) echo "usage: $0 [--rbac-only]" >&2; exit 2 ;;
esac

if [[ "$MODE" == "rbac-only" ]]; then TOTAL_STAGES=5; else TOTAL_STAGES=8; fi

API=10.10.82.50
CLUSTER=op-usxpress-dev
NS_PRIMARY=risingwave-2
NS_SECONDARY=risingwave
WORKDIR="$HOME/onprem-access"
ENV_FILE="$WORKDIR/tim.env"
mkdir -p "$WORKDIR"

if [[ "$MODE" == "rbac-only" ]]; then
  banner "Tim's op-dev permissions (RBAC only -- no cert, he can be away)"
else
  banner "Onboard Tim to $CLUSTER (namespace super-user)"
fi

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: pin the cluster, prove admin, report what exists"
say "Read-only. Nothing is created in this stage."

KCF=""; CTX=""
CANDS=""
[[ -n "${KUBECONFIG:-}" ]] && CANDS=$(printf '%s' "$KUBECONFIG" | tr ':' '\n')
for f in "$HOME/.kube/config" "$HOME"/.kube/*.yaml "$HOME"/.kube/*.yml "$HOME"/.kube/*.conf; do
  [[ -f "$f" ]] && CANDS="$CANDS
$f"
done
CANDS=$(printf '%s\n' "$CANDS" | grep -v '^$' | awk '!seen[$0]++' || true)
for f in $CANDS; do
  [[ -f "$f" ]] || continue
  for c in $(kubectl --kubeconfig "$f" config get-contexts -o name 2>/dev/null || true); do
    srv=$(kubectl --kubeconfig "$f" config view --minify --context "$c" \
            -o jsonpath='{.clusters[0].cluster.server}' 2>/dev/null || true)
    if [[ "$srv" == *"$API"* ]]; then KCF="$f"; CTX="$c"; break; fi
  done
  [[ -n "$CTX" ]] && break
done
if [[ -z "$CTX" ]]; then
  warn "no kubeconfig context points at $API ($CLUSTER). Cannot continue."
  note "Checked \$KUBECONFIG and $HOME/.kube/. Rebuild the dev kubeconfig first."
  exit 1
fi
say "context: $CTX"
say "file:    $KCF"

# Every call from here uses this one function. No bare kubectl below.
k() { kubectl --kubeconfig "$KCF" --context "$CTX" "$@"; }

SRV=$(k config view --minify -o jsonpath='{.clusters[0].cluster.server}')
if [[ "$SRV" != *"$API"* ]]; then
  warn "context resolves to $SRV, not $API. Refusing to continue."; exit 1
fi
printf '  %s✓%s pinned to %s (%s)\n' "$GREEN" "$RESET" "$SRV" "$CLUSTER"

ADMIN=$(k auth can-i '*' '*' --all-namespaces 2>/dev/null) || true
if [[ "${ADMIN%%$'\n'*}" != "yes" ]]; then
  warn "this identity is not cluster-admin on $CLUSTER; signing a CSR will fail."; exit 1
fi
printf '  %s✓%s caller is cluster-admin\n' "$GREEN" "$RESET"

for ns in "$NS_PRIMARY" "$NS_SECONDARY"; do
  if k get ns "$ns" >/dev/null 2>&1; then
    printf '  %s✓%s namespace %s exists\n' "$GREEN" "$RESET" "$ns"
  else
    warn "namespace $ns does not exist on $CLUSTER. Check the name before continuing."; exit 1
  fi
done

say ""
say "Anything already granted to Tim? (an empty result here is the expected case)"
EXIST=$(k get csr -o name 2>/dev/null | grep -i -e tim -e preble || true)
BIND=$(k get rolebinding -A -o wide 2>/dev/null | grep -i -e tim -e preble || true)
CBIND=$(k get clusterrolebinding -o wide 2>/dev/null | grep -i -e tim -e preble || true)
if [[ -z "$EXIST$BIND$CBIND" ]]; then
  note "  nothing found -- this is a first-time grant"
else
  warn "Tim already has objects on this cluster:"
  [[ -n "$EXIST" ]] && printf '    csr: %s\n' "$EXIST"
  [[ -n "$BIND"  ]] && printf '    rolebinding: %s\n' "$BIND"
  [[ -n "$CBIND" ]] && printf '    clusterrolebinding: %s\n' "$CBIND"
  note "If his cert merely EXPIRED, he reuses his key and only stages 3-4 are needed."
  confirm "Continue anyway?" || exit 0
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Tim's username, and the block to send him"
say "The CN becomes his Kubernetes username and appears in every audit log entry."
ask TIM_CN "Kubernetes username for Tim [timothy-preble]:"
[[ -z "$TIM_CN" ]] && TIM_CN="timothy-preble"
case "$TIM_CN" in
  *[!a-z0-9-]*) warn "use lowercase letters, digits and hyphens only"; exit 1 ;;
esac
write_env TIM_CN "$TIM_CN"
mkdir -p "$WORKDIR/$TIM_CN"

SEND="$WORKDIR/$TIM_CN/1-send-to-tim-key-and-csr.txt"
cat > "$SEND" <<EOF
Tim -- run this on your Mac. It creates a private key that never leaves your
laptop, and a CSR, which is public and safe to send back over Teams.

  mkdir -p ~/.kube/keys && chmod 700 ~/.kube/keys

  openssl genrsa -out ~/.kube/keys/$TIM_CN.key 4096
  chmod 600 ~/.kube/keys/$TIM_CN.key

  openssl req -new -key ~/.kube/keys/$TIM_CN.key \\
    -subj "/CN=$TIM_CN/O=risingwave-users" \\
    -out ~/.kube/keys/$TIM_CN.csr

  cat ~/.kube/keys/$TIM_CN.csr

Send back everything from -----BEGIN CERTIFICATE REQUEST----- to
-----END CERTIFICATE REQUEST----- inclusive.

Do NOT send the .key file. Nobody needs it, ever.
EOF
say ""
say "Written to: $SEND"
note "(macOS openssl handles all of the above; no GNU tools required)"
if [[ "$MODE" == "rbac-only" ]]; then
  say "Send it whenever suits -- it waits for him. This run stops before the cert."
  pause
else
  say "Send that to Tim now, then come back when he replies."
  pause "Sent? Press Enter when you have his CSR."
fi

if [[ "$MODE" != "rbac-only" ]]; then

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Verify the CSR he sent"
CSR="$WORKDIR/$TIM_CN/$TIM_CN.csr"
say "Paste Tim's CSR into the editor that opens, then save and close."
pause "Press Enter to open the editor."
: > "$CSR"
"${EDITOR:-nano}" "$CSR"

if ! openssl req -in "$CSR" -noout -subject >/dev/null 2>&1; then
  warn "that file is not a valid certificate request. Re-run this stage."; exit 1
fi
SUBJ=$(openssl req -in "$CSR" -noout -subject)
BITS=$(openssl req -in "$CSR" -noout -text | sed -n 's/.*Public-Key: (\([0-9]*\) bit).*/\1/p')
say "subject:  $SUBJ"
say "key size: ${BITS:-unknown} bit"

# Check the CN he actually used, rather than assuming he pasted the right block.
case "$SUBJ" in
  *"CN = $TIM_CN"*|*"CN=$TIM_CN"*) printf '  %s✓%s CN matches %s\n' "$GREEN" "$RESET" "$TIM_CN" ;;
  *) warn "CN in the CSR does not match '$TIM_CN'. Signing this would create a"
     warn "different user from the one being granted access below. Stopping."; exit 1 ;;
esac
case "$SUBJ" in
  *risingwave-users*) printf '  %s✓%s group is risingwave-users (grants nothing by itself)\n' "$GREEN" "$RESET" ;;
  *onprem-platform*) warn "this CSR carries an onprem-platform group, which is the CLUSTER-WIDE tier."
     warn "That is broader than the agreed scope. Ask Tim to regenerate with the block sent."; exit 1 ;;
  *) warn "unexpected O= in the subject. Check it before signing."; confirm "Sign anyway?" || exit 0 ;;
esac
if [[ -n "$BITS" && "$BITS" -lt 4096 ]]; then
  warn "key is only $BITS bit; the block asked for 4096."
  confirm "Sign anyway?" || exit 0
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Sign it"
warn "This creates a CertificateSigningRequest on $CLUSTER and approves it."
confirm "Sign a 1-year client cert for '$TIM_CN' on $CLUSTER?" || exit 0

k delete csr "$TIM_CN" --ignore-not-found >/dev/null
REQ=$(base64 < "$CSR" | tr -d '\n')
cat <<EOF | k apply -f - >/dev/null
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: $TIM_CN
spec:
  request: $REQ
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31536000
  usages:
  - client auth
EOF
k certificate approve "$TIM_CN" >/dev/null
CRT="$WORKDIR/$TIM_CN/$TIM_CN.crt"
for _ in 1 2 3 4 5 6 7 8 9 10; do
  k get csr "$TIM_CN" -o jsonpath='{.status.certificate}' 2>/dev/null | base64 -d > "$CRT" || true
  [[ -s "$CRT" ]] && break
  sleep 1
done
if [[ ! -s "$CRT" ]]; then
  warn "the CSR was approved but no certificate was issued after 10s."
  note "Check: k describe csr $TIM_CN -- a signer may not be running."; exit 1
fi
printf '  %s✓%s signed\n' "$GREEN" "$RESET"
openssl x509 -in "$CRT" -noout -subject -dates | sed 's/^/  /'
NOTAFTER=$(openssl x509 -in "$CRT" -noout -enddate | cut -d= -f2)
write_env TIM_CERT_EXPIRES "$NOTAFTER"
note "Set a calendar reminder 30 days before that date -- expiry is the only"
note "revocation control until OIDC lands."
pause

fi   # end stages 3-4 (need Tim)

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Grant: namespace super-user in $NS_PRIMARY and $NS_SECONDARY"
RBAC="$WORKDIR/$TIM_CN/rolebindings-$TIM_CN.yaml"
: > "$RBAC"
for ns in "$NS_PRIMARY" "$NS_SECONDARY"; do
  cat >> "$RBAC" <<EOF
---
# Namespace super-user for $TIM_CN. ClusterRole 'admin' used in a RoleBinding
# grants full control INSIDE $ns only -- including secrets, excluding the
# namespace object itself and resource quota. Recorded scope: not cluster-wide.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: risingwave-admin-$TIM_CN
  namespace: $ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: $TIM_CN
EOF
done
say "About to apply:"
sed 's/^/    /' "$RBAC"
say ""
say "Server-side dry run first:"
k apply --dry-run=server -f "$RBAC" 2>&1 | sed 's/^/    /' || {
  warn "the server rejected the dry run above. Nothing has been applied."; exit 1; }
say ""
# Re-assert the target immediately before writing. The context could have been
# changed in another window since stage 1.
SRV2=$(k config view --minify -o jsonpath='{.clusters[0].cluster.server}')
[[ "$SRV2" == *"$API"* ]] || { warn "context moved to $SRV2. Refusing to apply."; exit 1; }
confirm "Apply these two RoleBindings to $CLUSTER ($SRV2)?" || exit 0
k apply -f "$RBAC" | sed 's/^/    /'
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Prove the grant -- and prove the boundary holds"
say "A grant that has not had its limits tested has not been verified."
say ""
FAILED=0
check() { # check <expected yes|no> <description> <can-i args...>
  local want="$1" desc="$2"; shift 2
  local got=""
  got=$(k auth can-i "$@" --as="$TIM_CN" 2>/dev/null) || true
  got=${got%%$'\n'*}          # can-i prints "no" and exits 1; take the first line only
  [[ -n "$got" ]] || got=error
  if [[ "$got" == "$want" ]]; then
    printf '  %s✓%s %-52s %s\n' "$GREEN" "$RESET" "$desc" "$got"
  else
    printf '  %s✗%s %-52s %s (expected %s)\n' "$RED" "$RESET" "$desc" "$got" "$want"
    FAILED=1
  fi
}
say "MUST be allowed:"
for ns in "$NS_PRIMARY" "$NS_SECONDARY"; do
  check yes "create pods in $ns"        create pods       -n "$ns"
  check yes "delete pods in $ns"        delete pods       -n "$ns"
  check yes "read secrets in $ns"       get secrets       -n "$ns"
  check yes "exec into pods in $ns"     create pods/exec  -n "$ns"
done
say ""
say "MUST be denied (this half is the point):"
check no "read secrets in kube-system"        get secrets -n kube-system
check no "read secrets cluster-wide"          get secrets --all-namespaces
check no "list nodes"                         get nodes
check no "create a clusterrolebinding"        create clusterrolebindings
check no "delete pods in the default ns"      delete pods -n default
check no "delete pods in flux-system"         delete pods -n flux-system
say ""
if [[ "$FAILED" -eq 1 ]]; then
  warn "at least one check came out wrong. Do NOT hand this to Tim yet."
  note "A denial that reads 'yes' means the blast radius is bigger than agreed."
  exit 1
fi
printf '  %s✓ grant and boundary both verified%s\n' "$GREEN" "$RESET"
pause

if [[ "$MODE" != "rbac-only" ]]; then

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Send Tim his certificate and kubeconfig steps"
CA="$WORKDIR/$TIM_CN/op-usxpress-dev-ca.crt"
k config view --raw --minify -o jsonpath='{.clusters[0].cluster.certificate-authority-data}' \
  | base64 -d > "$CA"
[[ -s "$CA" ]] || { warn "could not extract the cluster CA from $KCF"; exit 1; }

OUT="$WORKDIR/$TIM_CN/2-send-to-tim-cert-and-kubeconfig.txt"
{
  echo "Tim -- you now have access to $CLUSTER inside $NS_PRIMARY and $NS_SECONDARY."
  echo "Everything below is public. Your private key stays where it is."
  echo
  echo "1. Save these two blocks on your Mac:"
  echo
  echo "----- signed cert: save as ~/.kube/keys/$TIM_CN.crt -----"
  cat "$CRT"
  echo "----- cluster CA: save as ~/.kube/keys/op-usxpress-dev-ca.crt -----"
  cat "$CA"
  echo
  echo "2. Build the kubeconfig (macOS-safe base64 -- the runbook's version is GNU-only):"
  echo
  echo "  mkdir -p ~/.kube/configs"
  echo "  chmod 600 ~/.kube/keys/$TIM_CN.crt ~/.kube/keys/op-usxpress-dev-ca.crt"
  echo "  CA_DATA=\$(base64 < ~/.kube/keys/op-usxpress-dev-ca.crt | tr -d '\\n')"
  echo "  CERT_DATA=\$(base64 < ~/.kube/keys/$TIM_CN.crt | tr -d '\\n')"
  echo "  KEY_DATA=\$(base64 < ~/.kube/keys/$TIM_CN.key | tr -d '\\n')"
  echo
  # Unindented deliberately: a plain <<EOF heredoc only ends on an EOF at column 0.
  echo "cat > ~/.kube/configs/$CLUSTER <<EOF"
  echo "apiVersion: v1"
  echo "kind: Config"
  echo "clusters:"
  echo "- name: $CLUSTER"
  echo "  cluster:"
  echo "    server: https://$API:6443"
  echo "    certificate-authority-data: \${CA_DATA}"
  echo "contexts:"
  echo "- name: $CLUSTER"
  echo "  context:"
  echo "    cluster: $CLUSTER"
  echo "    namespace: $NS_PRIMARY"
  echo "    user: $TIM_CN"
  echo "current-context: $CLUSTER"
  echo "users:"
  echo "- name: $TIM_CN"
  echo "  user:"
  echo "    client-certificate-data: \${CERT_DATA}"
  echo "    client-key-data: \${KEY_DATA}"
  echo "EOF"
  echo
  echo "  chmod 600 ~/.kube/configs/$CLUSTER"
  echo "  export KUBECONFIG=~/.kube/configs/$CLUSTER"
  echo
  echo "3. Smoke tests. These expectations are for a NAMESPACE admin, so two of"
  echo "   them are meant to say no -- that is the scope working, not a fault:"
  echo
  echo "  kubectl auth whoami                              # -> $TIM_CN"
  echo "  kubectl get pods -n $NS_PRIMARY                  # -> your pods"
  echo "  kubectl get secrets -n $NS_PRIMARY               # -> allowed, this is your namespace"
  echo "  kubectl get nodes                                # -> Forbidden, expected"
  echo "  kubectl get pods -n kube-system                  # -> Forbidden, expected"
  echo
  echo "Your cert expires $NOTAFTER. Ask for a re-issue about a month before;"
  echo "you keep the same key and only the cert is replaced."
  echo
  echo "Note: rw2-pg.op-dev.usxpress.io does not exist. Exposing RW-2 postgres"
  echo "outside the cluster is an open decision (INFRA-1495), not a broken record."
  echo "rw2-sql.op-dev.usxpress.io:4567 is live if SQL is what you need."
} > "$OUT"
say "Written to: $OUT"
say "Send that file's contents to Tim."
note "It contains no private key material -- cert and CA are both public."
pause

fi   # end stage 7 (needs the signed cert)

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Make Git say what the cluster says"
warn "The RoleBindings were applied live. They are NOT yet in Git."
say ""
say "op-usxpress-dev is rebuilt to validate. A hand-applied binding does not"
say "survive that -- this is the INFRA-1589 lesson, and it has bitten before."
say ""
say "The manifest to land:"
say "  $RBAC"
say ""
step "Clone or refresh the cluster repo and branch from op-dev"
step "Copy the file in, and add it to that directory's kustomization.yaml --"
note "  a file Flux does not enumerate is a file Flux does not apply"
step "Read 'git diff origin/op-dev' in full before pushing, including lines you"
note "  did not mean to change"
step "Open the PR with the base pinned: gh pr create --base op-dev --fill"
say ""
SKIPPED+=("land $RBAC on the op-dev branch, or the next rebuild drops Tim's access")
if [[ "$MODE" == "rbac-only" ]]; then
  SKIPPED+=("when Tim is back: re-run this WITHOUT --rbac-only for his cert (stages 3, 4, 7)")
else
  SKIPPED+=("calendar reminder 30 days before $NOTAFTER to re-issue Tim's cert")
fi
pause

finish
if [[ "$MODE" == "rbac-only" ]]; then
  say "The permission model is live and proved: user '$TIM_CN' is a super-user in"
  say "$NS_PRIMARY and $NS_SECONDARY on $CLUSTER, and nowhere else."
  say "He has no credential yet, so it grants nobody anything until he is issued one."
  say ""
  say "When he is back:  bash $0"
else
  say "Tim is a super-user in $NS_PRIMARY and $NS_SECONDARY on $CLUSTER, and nowhere else."
fi
say "Files: $WORKDIR/$TIM_CN/"
say ""
