#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Argo CD SSO on op-usxpress-dev via AWS Identity Center (SAML + Dex).
# INFRA-1639 step 3. Steps 1, 2 and 4 are already merged (route, configs.cm.url,
# configs.rbac). This covers only what a console can do and a script cannot.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE="${ENV_FILE:-$HOME/argocd-sso-dev.env}"
OUT="${OUT:-$HOME/argocd-dex-saml-dev.yaml}"
ARGOCD_URL="https://argocd.op-dev.usxpress.io"
CALLBACK="$ARGOCD_URL/api/dex/callback"
GROUP="onprem-platform-admins"

# Every aws call is pinned to an explicit profile (CLAUDE.md rule 2). Without it
# the calls used the DEFAULT profile, which has no credentials -- so preflight
# reported "no Identity Center instance reachable" while the same command with
# --profile usx-dev returned it instantly. An unpinned aws call is a bug even
# when it works.
PROFILE="${PROFILE:-${AWS_PROFILE:-}}"
if [[ -z "$PROFILE" ]]; then
  printf '  Set the AWS profile first, explicitly:\n\n'
  printf '    PROFILE=usx-dev %s\n\n' "$0"
  printf '  Identity Center lives in the management account, so the profile that\n'
  printf '  can CREATE the application is probably not usx-dev. Use the profile\n'
  printf '  for account 660075424663 with an admin permission set.\n'
  exit 2
fi
AWS() { aws --profile "$PROFILE" "$@"; }

banner "Argo CD SSO on op-usxpress-dev — AWS Identity Center (SAML via Dex)"
say "  AWS profile: $PROFILE"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — can you actually do this?"
say "Two things gate everything below. Check both now rather than at stage 5."
step "You need IAM Identity Center ADMIN in the management account. Creating a"
step "customer managed application is not something a delegated account can do."
step "Argo on dev must be reachable: $ARGOCD_URL"
say ""
say "Checking the Argo endpoint (bypassing DNS, in case of a stale negative cache):"
if curl -sS -o /dev/null -w '  HTTP %{http_code}\n' --max-time 10 \
     --resolve "argocd.op-dev.usxpress.io:443:10.10.82.21" "$ARGOCD_URL/" 2>/dev/null; then
  say "  A 200 or 302 here is fine. Anything else: stop and fix the route first."
else
  say "  ${YELLOW}Could not reach it. Corp VPN? Then re-run.${RESET}"
fi
say ""
say "Locating the Identity Center instance. sso-admin only answers in the"
say "MANAGEMENT account, so AccessDenied here means you are not on it yet."
IDC_REGION=""; IDC_ARN=""; IDC_STORE=""; IDC_OWNER=""
for r in us-east-1 us-east-2; do
  out=$(AWS sso-admin list-instances --region "$r" \
        --query 'Instances[0].[InstanceArn,IdentityStoreId,OwnerAccountId]' \
        --output text 2>&1) || true
  case "$out" in
    arn:aws:sso*) IDC_REGION="$r"
                  IDC_ARN=$(printf '%s' "$out" | awk '{print $1}')
                  IDC_STORE=$(printf '%s' "$out" | awk '{print $2}')
                  IDC_OWNER=$(printf '%s' "$out" | awk '{print $3}')
                  break ;;
    *) say "  $r: $(printf '%s' "$out" | head -1 | cut -c1-90)" ;;
  esac
done
if [[ -z "$IDC_REGION" ]]; then
  warn "No Identity Center instance reachable with your current credentials."
  say ""
  say "Sign in to the MANAGEMENT account with an admin permission set first:"
  say "  https://usxpress.awsapps.com/start"
  say "Then export the right profile and re-run this wizard. Do not proceed by"
  say "clicking around the console -- if sso-admin cannot see the instance, the"
  say "application you create will be in the wrong place or not creatable at all."
  exit 1
fi
# list-instances ANSWERS FROM MEMBER ACCOUNTS. It proves the org has an instance,
# not that you can administer it -- on 2026-08-24 the usx-dev profile (account
# 700736442855) returned the instance owned by 660075424663, which would have
# waved the user through to the create step to fail there. Test a call that
# actually requires management-account permissions.
say ""
say "Instance found. Now testing whether you can ADMINISTER it, which is a"
say "different question -- list-instances answers from member accounts too."
WHOAMI=$(AWS sts get-caller-identity --query Account --output text 2>/dev/null || echo "?")
probe=$(AWS sso-admin list-applications --instance-arn "$IDC_ARN" \
        --region "$IDC_REGION" --max-results 1 --output text 2>&1) || true
case "$probe" in
  *AccessDenied*|*not\ authorized*|*UnauthorizedException*)
    warn "You are in account $WHOAMI and cannot administer the instance."
    say ""
    say "  instance owner : $IDC_OWNER"
    say "  you            : $WHOAMI"
    say ""
    say "Sign in to $IDC_OWNER with an admin permission set:"
    say "  https://usxpress.awsapps.com/start"
    say "then export that profile and re-run. Creating the application needs"
    say "write access in the management account; browsing the console with"
    say "member-account credentials will fail at the create step, not before."
    exit 1 ;;
esac
say "  ${GREEN}sso-admin write path reachable from account $WHOAMI${RESET}"

say ""
say "  ${GREEN}region ${RESET}$IDC_REGION"
say "  ${GREEN}owner  ${RESET}$IDC_OWNER"
say "  ${GREEN}store  ${RESET}$IDC_STORE"
write_env IDC_REGION "$IDC_REGION"
write_env IDC_IDENTITY_STORE_ID "$IDC_STORE"

say ""
say "Checking the group exists before you assign it at stage 4:"
gid=$(AWS identitystore list-groups --identity-store-id "$IDC_STORE" \
        --region "$IDC_REGION" \
        --query "Groups[?DisplayName=='$GROUP'].GroupId" --output text 2>&1) || true
case "$gid" in
  ""|*error*|*Denied*) warn "Could not confirm '$GROUP' exists: $(printf '%s' "$gid" | head -1 | cut -c1-70)"
                       say "  If that group does not exist, stage 4 has nothing to assign and"
                       say "  configs.rbac maps a group nobody is in." ;;
  *) say "  ${GREEN}$GROUP${RESET} -> $gid"; write_env IDC_GROUP_ID "$gid" ;;
esac
confirm "Continue?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the SAML application"
open_url "https://${IDC_REGION}.console.aws.amazon.com/singlesignon/home?region=${IDC_REGION}#!/applications"
step "Applications → Add application → 'I have an application I want to set up'"
step "→ SAML 2.0 → Next."
step "Display name: Argo CD (op-usxpress-dev)"
say ""
note "Console wording shifts between revisions. If these labels do not match"
note "what you see, follow the SAML 2.0 customer-managed path and keep going."
pause "Created the application?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Point it at Argo's callback"
say "In the application's configuration, under 'Application metadata', choose"
say "'Manually type your metadata values' and enter BOTH of these as the SAME URL:"
say ""
say "  ${BOLD}Application ACS URL${RESET}       $CALLBACK"
say "  ${BOLD}Application SAML audience${RESET} $CALLBACK"
say ""
step "They are identical on purpose. Dex uses the callback as its entityIssuer,"
step "so an audience that differs by even a trailing slash fails validation with"
step "an error that names the assertion, not the URL."
pause "Both values saved?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Assign the group"
step "On the application: Assigned users and groups → Assign users and groups."
step "Assign the GROUP ${BOLD}$GROUP${RESET} — not individual users."
say ""
say "That is the same group the cluster SSO path grants through"
say "aws-iam-authenticator (INFRA-1638), and the same one configs.rbac maps to"
say "role:admin. One group across both layers."
pause "Group assigned?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Attribute mappings — the step that decides whether this works"
step "On the application: Actions → Edit attribute mappings. Set:"
say ""
say "  ${BOLD}Subject${RESET}  \${user:email}      format emailAddress"
say "  ${BOLD}email${RESET}    \${user:email}      format basic"
say "  ${BOLD}groups${RESET}   \${user:groups}     format basic"
say ""
warn "READ THIS. Identity Center does not always offer \${user:groups},"
say "and where it does the value may be group GUIDs rather than names. If you"
say "cannot emit a usable groups attribute, SSO will still LOG IN and then land"
say "with no permissions — an empty UI with access errors, which looks like a"
say "broken login but is authorisation."
say ""
say "If groups are unavailable or come through as GUIDs, the fallback is to map"
say "identities directly in configs.rbac instead of by group, e.g."
say "  g, doke@usxpress.com, role:admin"
say "That trades the single-group model for a list, and it is a real decision —"
say "note it on INFRA-1639 rather than deciding it silently."
ask GROUPS_ATTR_OK "Could you map a groups attribute to readable names? (yes/no/guids)"
write_env GROUPS_ATTR_OK "$GROUPS_ATTR_OK"
pause "Attribute mappings saved?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Capture the IdP metadata and build the dex.config"
step "On the application, under 'IAM Identity Center metadata', download the"
step "'IAM Identity Center SAML metadata file' (an XML file)."
say ""
ask META_PATH "Full path to the downloaded XML file:"
if [[ ! -f "$META_PATH" ]]; then
  say "${RED}No file at $META_PATH — cannot continue.${RESET}"
  exit 1
fi
say ""
say "Extracting the SSO URL and signing certificate..."
python3 - "$META_PATH" "$OUT" "$CALLBACK" <<'PYEOF'
import base64, re, sys, xml.etree.ElementTree as ET
meta, out, callback = sys.argv[1], sys.argv[2], sys.argv[3]
ns = {"md": "urn:oasis:names:tc:SAML:2.0:metadata",
      "ds": "http://www.w3.org/2000/09/xmldsig#"}
root = ET.parse(meta).getroot()

sso = None
for s in root.iter("{urn:oasis:names:tc:SAML:2.0:metadata}SingleSignOnService"):
    if s.get("Binding", "").endswith("HTTP-Redirect"):
        sso = s.get("Location"); break
if sso is None:
    sys.exit("could not find a HTTP-Redirect SingleSignOnService in the metadata")

certs = [c.text for c in root.iter(
    "{http://www.w3.org/2000/09/xmldsig#}X509Certificate") if c.text]
if not certs:
    sys.exit("no X509Certificate in the metadata")
der = re.sub(r"\s+", "", certs[0])
pem = ("-----BEGIN CERTIFICATE-----\n"
       + "\n".join(der[i:i+64] for i in range(0, len(der), 64))
       + "\n-----END CERTIFICATE-----\n")
# caData is the base64 of the PEM. NOT the raw DER the XML already contains --
# double-encoding here produces "failed to parse CA" at login and nothing sooner.
ca = base64.b64encode(pem.encode()).decode()

open(out, "w").write("""# INFRA-1639 step 3 -- generated by scripts/wizard-argocd-sso-dev.sh
# Paste into infrastructure/argocd/helmrelease.yaml on branch op-dev, under
# spec.values, and set dex.enabled: true in the same edit.
#
# NO CLIENT SECRET EXISTS FOR SAML. caData below is the IdP's PUBLIC signing
# certificate, so this is safe in git and needs no ExternalSecret -- which also
# means argocd-secret is never touched, and op-dev's server.secretkey (from the
# 49-day-old raw install it adopted) survives untouched.
    dex:
      enabled: true
    configs:
      cm:
        dex.config: |
          connectors:
            - type: saml
              id: aws
              name: AWS IAM Identity Center
              config:
                ssoURL: %s
                # entityIssuer MUST equal the Application SAML audience set in
                # Identity Center, character for character.
                entityIssuer: %s
                redirectURI: %s
                usernameAttr: email
                emailAttr: email
                groupsAttr: groups
                caData: |
                  %s
""" % (sso, callback, callback, ca))
print("  ssoURL : %s" % sso)
print("  caData : %d chars (base64 of the PEM)" % len(ca))
print("  written: %s" % out)
PYEOF
write_env ARGOCD_DEX_CONFIG "$OUT"
say ""
say "${GREEN}Written to $OUT${RESET}"
pause "Ready to land it?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Land it, then prove it with a real login"
step "Add the block from $OUT to infrastructure/argocd/helmrelease.yaml on op-dev,"
step "open a PR against op-dev, merge, then reconcile:"
say ""
say "  flux --context admin@op-usxpress-dev -n flux-system reconcile source git infra"
say "  flux --context admin@op-usxpress-dev -n flux-system reconcile kustomization argocd"
say "  scripts/flux-revision-drift.sh --cluster op-dev"
say ""
say "${BOLD}argocd-server reads dex.config at startup.${RESET} If the Helm upgrade does not"
say "restart it, the old config is still being served while everything reports"
say "Ready. Check the pod age:"
say ""
say "  kubectl --context admin@op-usxpress-dev -n argocd get pods \\"
say "    -l app.kubernetes.io/name=argocd-server"
say ""
say "${BOLD}Then the only verification that counts:${RESET} open $ARGOCD_URL in a"
say "browser, click LOG IN VIA AWS IAM IDENTITY CENTER, and confirm you land"
say "with actual permissions — applications visible, not an empty page."
say ""
say "  argocd login argocd.op-dev.usxpress.io --sso"
say "  argocd account get-user-info      # expect groups: [$GROUP]"
say ""
warn "A green HelmRelease and a successful redirect both prove nothing."
say "An empty UI after a successful login means the groups claim did not arrive"
say "or does not match configs.rbac — go back to stage 5, not to the connector."
confirm "Did a real login land with role:admin?"

finish
