/^\t"os"$/ { print "\t\"maps\""; print; print "\t\"regexp\""; print "\t\"slices\""; print "\t\"strings\""; next }
/TODO\(exercise\)/ {
  print "\tfor _, key := range slices.Sorted(maps.Keys(ui.ConfigVars)) {"
  print "\t\tif !identityKey(key) {"
  print "\t\t\tcontinue"
  print "\t\t}"
  print "\t\tif !identityValue(ui.ConfigVars[key]) {"
  print "\t\t\tcontinue"
  print "\t\t}"
  print "\t\tproblems = append(problems, fmt.Errorf("
  print "\t\t\t\"ui.configVars.%s: application identity must not be hardcoded here. \"+"
  print "\t\t\t\t\"The platform generates this value on every deploy; remove the key and \"+"
  print "\t\t\t\t\"read it from the configuration the platform serves at runtime\", key))"
  print "\t}"
  next
}
{ print }
END {
  print ""
  print "// guidRE matches a bare identity, optionally carrying a scope suffix such as"
  print "// \"<guid>/.default\" or \"<guid>/user_impersonation\"."
  print "var guidRE = regexp.MustCompile("
  print "\t`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}(/[A-Za-z._]+)?$`)"
  print ""
  print "// identityValue reports whether v has the shape of an identity we generate."
  print "func identityValue(v string) bool { return guidRE.MatchString(v) }"
  print ""
  print "// identityKey reports whether a config key names something the platform owns."
  print "//"
  print "// TENANT_ID is deliberately absent: a tenant identifier is constant for the"
  print "// whole organisation and does not change when an app registration is recreated,"
  print "// so pinning it is harmless."
  print "var identitySuffixes = []string{\"CLIENT_ID\", \"APP_ID\", \"SCOPES\", \"AUDIENCE\"}"
  print ""
  print "func identityKey(k string) bool {"
  print "\tup := strings.ToUpper(k)"
  print "\tfor _, suffix := range identitySuffixes {"
  print "\t\tif strings.HasSuffix(up, suffix) {"
  print "\t\t\treturn true"
  print "\t\t}"
  print "\t}"
  print "\treturn false"
  print "}"
}
