
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cross-cluster-app-secrets
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: infra
  path: ./infrastructure/cross-cluster-app-secrets
  prune: true
  wait: false
  timeout: 5m
  dependsOn:
  - name: cross-cluster-eso
  - name: app-namespaces
